//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Birth_First.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Birth_First.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Image URL can&apos;t recognize. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string info_image_error {
            get {
                return ResourceManager.GetString("info_image_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I created a new file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string info_newfile {
            get {
                return ResourceManager.GetString("info_newfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please input only numbers. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string info_number {
            get {
                return ResourceManager.GetString("info_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Return に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string info_return {
            get {
                return ResourceManager.GetString("info_return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In this configration,
        ///If you can be got API rate Limits. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string info_rt_limits {
            get {
                return ResourceManager.GetString("info_rt_limits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In this configuration ,
        ///it can be that seemes like spam.
        ///You may troble for your follower... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string info_toomach {
            get {
                return ResourceManager.GetString("info_toomach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The number is not valid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string info_unvaild {
            get {
                return ResourceManager.GetString("info_unvaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chino-Chan is fluffy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string mohumohu {
            get {
                return ResourceManager.GetString("mohumohu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Birth can&apos;t run multiple. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string multiple_startup_1 {
            get {
                return ResourceManager.GetString("multiple_startup_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Birth is already running. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string multiple_startup_title {
            get {
                return ResourceManager.GetString("multiple_startup_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Network Error! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string network_error_1 {
            get {
                return ResourceManager.GetString("network_error_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Birth need to conect Internet.
        ///Please confirm to your network. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string network_error_2 {
            get {
                return ResourceManager.GetString("network_error_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you close the authentication of Birth?
        ///
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string pincode_check_1 {
            get {
                return ResourceManager.GetString("pincode_check_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you will close now, pin isn&apos;t saved.
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string pincode_check_2 {
            get {
                return ResourceManager.GetString("pincode_check_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please input pin under the box of the window. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string pincode_check_3 {
            get {
                return ResourceManager.GetString("pincode_check_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The pin can&apos;t be recognized normal. 
        ///
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string pincode_error_1 {
            get {
                return ResourceManager.GetString("pincode_error_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please try again.
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string pincode_error_2 {
            get {
                return ResourceManager.GetString("pincode_error_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Account に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string setting_account_1 {
            get {
                return ResourceManager.GetString("setting_account_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tweets by user who blocked from this acc don&apos;t RT. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string setting_account_2 {
            get {
                return ResourceManager.GetString("setting_account_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blocked keywords に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string setting_ng_1 {
            get {
                return ResourceManager.GetString("setting_ng_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blocked accounts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string setting_ng_2 {
            get {
                return ResourceManager.GetString("setting_ng_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable Blocked keywords に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string setting_ng_3 {
            get {
                return ResourceManager.GetString("setting_ng_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable Blocked acconuts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string setting_ng_4 {
            get {
                return ResourceManager.GetString("setting_ng_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset to Retweets に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string setting_reset_1 {
            get {
                return ResourceManager.GetString("setting_reset_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete all Accounts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string setting_reset_2 {
            get {
                return ResourceManager.GetString("setting_reset_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete all Blocked Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string setting_reset_3 {
            get {
                return ResourceManager.GetString("setting_reset_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Blocked keywords に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string setting_reset_4 {
            get {
                return ResourceManager.GetString("setting_reset_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Blocked accounts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string setting_reset_5 {
            get {
                return ResourceManager.GetString("setting_reset_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset All Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string setting_reset_6 {
            get {
                return ResourceManager.GetString("setting_reset_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of times of retweets.　 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string setting_retweet_1 {
            get {
                return ResourceManager.GetString("setting_retweet_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retweet interval (s)　 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string setting_retweet_2 {
            get {
                return ResourceManager.GetString("setting_retweet_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retweet retweets. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string setting_retweet_3 {
            get {
                return ResourceManager.GetString("setting_retweet_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retweet my tweets. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string setting_retweet_4 {
            get {
                return ResourceManager.GetString("setting_retweet_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tweet the result at the end. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string setting_retweet_5 {
            get {
                return ResourceManager.GetString("setting_retweet_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   public に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string setting_retweet_6 {
            get {
                return ResourceManager.GetString("setting_retweet_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tweet&apos;s extraction from に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string setting_retweet_7 {
            get {
                return ResourceManager.GetString("setting_retweet_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retweets に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string setting_subject1 {
            get {
                return ResourceManager.GetString("setting_subject1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Acounts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string setting_subject2 {
            get {
                return ResourceManager.GetString("setting_subject2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Theme に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string setting_subject3 {
            get {
                return ResourceManager.GetString("setting_subject3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blocked Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string setting_subject4 {
            get {
                return ResourceManager.GetString("setting_subject4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string setting_subject5 {
            get {
                return ResourceManager.GetString("setting_subject5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About Birth に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string setting_subject6 {
            get {
                return ResourceManager.GetString("setting_subject6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   　　　Theme　 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string setting_theme_1 {
            get {
                return ResourceManager.GetString("setting_theme_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   　　　Wallpaper に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string setting_theme_2 {
            get {
                return ResourceManager.GetString("setting_theme_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   　　　Opacity of the wallpaper に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string setting_theme_3 {
            get {
                return ResourceManager.GetString("setting_theme_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   　　　Language　 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string setting_theme_4 {
            get {
                return ResourceManager.GetString("setting_theme_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///    tweets were retweeted.　
        ///#birth_rt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string tweet_propaganda {
            get {
                return ResourceManager.GetString("tweet_propaganda", resourceCulture);
            }
        }
    }
}
